name: Build and Deploy Pelican site
on:
  push:
  workflow_run:
    inputs:
      test-settings:
        type: string
        default: "pelicanconf.py"
      settings:
        type: string
        default: "publishconf.py"
      output-path:
        type: string
        default: "output"
      cache-path:
        type: string
        default: "cache"
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  Build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install --no-cache-dir -r requirements.txt
      - name: Build Pelican site
        run: pelican --settings ${{ inputs.test-settings }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.output-path }}
          retention-days: 7
  Build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install requirements
        run: pip install --no-cache-dir -r requirements.txt
      - name: Build Pelican site
        run: pelican --settings ${{ inputs.settings }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ inputs.output-path }}
          retention-days: 7
  Deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v4

      - name: Set up SSH key
        run: |
          eval $(ssh-agent -s)
          ssh-add <(echo "${{ secrets.DEPLOY_SSH_KEY }}")
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_HOST_KEY }}" > ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          echo "put -r ${{ inputs.output-path }}/*" | sftp ${{ secrets.DEPLOY_USERNAME }}@${{ secrets.DEPLOY_HOST }}:${{ secrets.DEPLOY_DIR }}
